targetPort: 3000

ingress:
  enable: true
  host: cs-agent-api-dev.whales-market.site

replicas: 1

envFrom:
  configMaps:
    - name: dev-common
    - name: dev-postgres
    - name: dev-redis
    - name: dev-vectordb
    - name: cs-agent-api

resources:
  requests:
    cpu: '50m'
    memory: '200Mi'
  limits:
    cpu: '200m'
    memory: '400Mi'

workers:
  - name: dev-whales-market-cs-agent-worker
    replicas: 1
    envFrom:
      configMaps:
        - name: cs-agent-worker
    resources:
      requests:
        cpu: '50m'
        memory: '200Mi'
      limits:
        cpu: '200m'
        memory: '400Mi'

healthCheck:
  enable: true
  path: /health
